spring:
  application:
    name: backend_thunderfood

  datasource:
    url: jdbc:mysql://localhost:3306/db_thunderfood?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Tự tạo bảng nếu chưa có, cập nhật nếu đã có
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  flyway:
    enabled: false   # Tắt Flyway, dùng Hibernate quản lý schema

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com       # TODO: thay bằng email của bạn
    password: your-app-password          # TODO: thay bằng App Password của Gmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000       # 1 ngày (ms)
  refresh-token:
    expiration: 604800000    # 7 ngày (ms)